app:
  name: duniversity-deployment

replicaCount: 1


image:
  repository: asadoblivion/duniversity-college-portal
  tag: v1.0

ports:
  containerPort: 3000

# mysql parameters
mysql_replicaCount: 2
mysql_terminationGracePeriodSeconds: 30
mysql_image: 
  repository: mariadb
  tag: latest
mysql_ports:
  containerPort: 3306
mysql_accessModes: [ReadWriteOnce]